/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminMenu: typeof import('./src/components/navbar/AdminMenu/index.vue')['default']
    AdvanceMenu: typeof import('./src/components/AdvanceMenu.vue')['default']
    ApexChart: typeof import('./src/components/ApexChart.vue')['default']
    AppMenu: typeof import('./src/components/navbar/AppMenu/index.vue')['default']
    BAccordion: typeof import('bootstrap-vue-next/components/BAccordion')['BAccordion']
    BAccordionItem: typeof import('bootstrap-vue-next/components/BAccordion')['BAccordionItem']
    BackToTop: typeof import('./src/components/BackToTop.vue')['default']
    BAlert: typeof import('bootstrap-vue-next/components/BAlert')['BAlert']
    BBadge: typeof import('bootstrap-vue-next/components/BBadge')['BBadge']
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BCard: typeof import('bootstrap-vue-next/components/BCard')['BCard']
    BCardBody: typeof import('bootstrap-vue-next/components/BCard')['BCardBody']
    BCardFooter: typeof import('bootstrap-vue-next/components/BCard')['BCardFooter']
    BCardHeader: typeof import('bootstrap-vue-next/components/BCard')['BCardHeader']
    BCardTitle: typeof import('bootstrap-vue-next/components/BCard')['BCardTitle']
    BCol: typeof import('bootstrap-vue-next/components/BContainer')['BCol']
    BCollapse: typeof import('bootstrap-vue-next/components/BCollapse')['BCollapse']
    BContainer: typeof import('bootstrap-vue-next/components/BContainer')['BContainer']
    BDropdown: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdown']
    BDropdownItem: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdownItem']
    BForm: typeof import('bootstrap-vue-next/components/BForm')['BForm']
    BFormFile: typeof import('bootstrap-vue-next/components/BFormFile')['BFormFile']
    BFormGroup: typeof import('bootstrap-vue-next/components/BFormGroup')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next/components/BFormInput')['BFormInput']
    BFormRadio: typeof import('bootstrap-vue-next/components/BFormRadio')['BFormRadio']
    BFormRadioGroup: typeof import('bootstrap-vue-next/components/BFormRadio')['BFormRadioGroup']
    BFormSelect: typeof import('bootstrap-vue-next/components/BFormSelect')['BFormSelect']
    BFormTextarea: typeof import('bootstrap-vue-next/components/BFormTextarea')['BFormTextarea']
    BInputGroup: typeof import('bootstrap-vue-next/components/BInputGroup')['BInputGroup']
    BModal: typeof import('bootstrap-vue-next/components/BModal')['BModal']
    BOffcanvas: typeof import('bootstrap-vue-next/components/BOffcanvas')['BOffcanvas']
    BProgress: typeof import('bootstrap-vue-next/components/BProgress')['BProgress']
    BProgressBar: typeof import('bootstrap-vue-next/components/BProgress')['BProgressBar']
    BRow: typeof import('bootstrap-vue-next/components/BContainer')['BRow']
    BTab: typeof import('bootstrap-vue-next/components/BTabs')['BTab']
    BTableSimple: typeof import('bootstrap-vue-next/components/BTable')['BTableSimple']
    BTabs: typeof import('bootstrap-vue-next/components/BTabs')['BTabs']
    BTbody: typeof import('bootstrap-vue-next/components/BTable')['BTbody']
    BTd: typeof import('bootstrap-vue-next/components/BTable')['BTd']
    BTh: typeof import('bootstrap-vue-next/components/BTable')['BTh']
    BThead: typeof import('bootstrap-vue-next/components/BTable')['BThead']
    BTr: typeof import('bootstrap-vue-next/components/BTable')['BTr']
    CategoryMenu: typeof import('./src/components/CategoryMenu.vue')['default']
    ChoicesSelect: typeof import('./src/components/ChoicesSelect.vue')['default']
    CustomGLightbox: typeof import('./src/components/CustomGLightbox.vue')['default']
    CustomStickyElement: typeof import('./src/components/CustomStickyElement.vue')['default']
    CustomTinySlider: typeof import('./src/components/CustomTinySlider.vue')['default']
    DropDown: typeof import('./src/components/DropDown.vue')['default']
    LogoBox: typeof import('./src/components/LogoBox.vue')['default']
    MegaMenuDropdown: typeof import('./src/components/MegaMenuDropdown.vue')['default']
    MenuItem: typeof import('./src/components/navbar/AdminMenu/MenuItem.vue')['default']
    MenuItemLink: typeof import('./src/components/navbar/AdminMenu/MenuItemLink.vue')['default']
    MenuItemWithChildren: typeof import('./src/components/navbar/AdminMenu/MenuItemWithChildren.vue')['default']
    MobileNavbarToggler: typeof import('./src/components/MobileNavbarToggler.vue')['default']
    NavSearch: typeof import('./src/components/NavSearch.vue')['default']
    NavSearchDropdown: typeof import('./src/components/NavSearchDropdown.vue')['default']
    ProfileDropdown: typeof import('./src/components/ProfileDropdown.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShopCart: typeof import('./src/components/ShopCart.vue')['default']
    StickyHeader: typeof import('./src/components/StickyHeader.vue')['default']
  }
  export interface GlobalDirectives {
    vBToggle: typeof import('bootstrap-vue-next/directives/BToggle')['vBToggle']
    vBTooltip: typeof import('bootstrap-vue-next/directives/BTooltip')['vBTooltip']
  }
}
